<!DOCTYPE html>
<html>
<head>
    <title>Sample Order PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            margin-top: 20px;
            font-weight: bold;
            text-align: right;
        }
    </style>
</head>
<body>
    <h1>Sample Order</h1>
    <p><strong>Order ID:</strong> {{ $sampleOrder->id }}</p>
    <p><strong>Customer Name:</strong> {{ $sampleOrder->customer->name }}</p>
    <p><strong>Order Name:</strong> {{ $sampleOrder->name }}</p>
    <p><strong>Wanted Delivery Date:</strong> {{ $sampleOrder->wanted_delivery_date }}</p>
    <p><strong>Special Notes:</strong> {{ $sampleOrder->special_notes }}</p>
    <p><strong>Generated By:</strong> {{ $printedBy }}</p>
    <p><strong>Generated Date & Time:</strong> {{ now() }}</p>

    <h2>Order Items</h2>
    <table>
        <thead>
            <tr>
                <th>Item Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($orderDescriptions as $description)
                <tr>
                    <td>{{ $description->item_name }}</td>
                    <td>{{ $description->quantity }}</td>
                    <td>{{ $description->price }}</td>
                    <td>{{ $description->total }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p><strong>Grand Total:</strong> {{ $grandTotal }}</p>
    </div>
</body>
</html>
