<?php

// config/database-records.php
return [
    'models' => [
        'additional_order_discounts' => [
            'label' => 'Additional Order Discounts',
            'model' => \App\Models\AdditionalOrderDiscount::class,
            'fields' => [
                'id'            => 'ID',
                'site_id'       => 'Site',
                'order_type'    => 'Order Type',
                'order_id'      => 'Order ID',
                'amount'        => 'Amount',
                'description'   => 'Description',
                'recorded_date' => 'Recorded Date',
                'remarks'       => 'Remarks',
                'status'        => 'Status',
                'created_by'    => 'Created By',
                'updated_by'    => 'Updated By',
                'created_at'    => 'Created At',
                'updated_at'    => 'Updated At',
            ],
        ],
        
        'additional_order_expenses' => [
            'label' => 'Additional Order Expenses',
            'model' => \App\Models\AdditionalOrderExpense::class,
            'fields' => [
                'id'            => 'ID',
                'site_id'       => 'Site',
                'order_type'    => 'Order Type',
                'order_id'      => 'Order ID',
                'amount'        => 'Amount',
                'description'   => 'Description',
                'recorded_date' => 'Recorded Date',
                'remarks'       => 'Remarks',
                'status'        => 'Status',
                'created_by'    => 'Created By',
                'updated_by'    => 'Updated By',
                'created_at'    => 'Created At',
                'updated_at'    => 'Updated At',
            ],
        ],
        
        'assign_daily_operations' => [
            'label' => 'Assign Daily Operations',
            'model' => \App\Models\AssignDailyOperation::class,
            'fields' => [
                'id'             => 'ID',
                'site_id'        => 'Site',
                'order_type'     => 'Order Type',
                'order_id'       => 'Order ID',
                'operation_date' => 'Operation Date',
                'status'         => 'Status',
                'created_by'     => 'Created By',
                'updated_by'     => 'Updated By',
                'created_at'     => 'Created At',
                'updated_at'     => 'Updated At',
                'deleted_at'     => 'Deleted At',
            ],
        ],

        'assign_daily_operation_labels' => [
            'label' => 'Assign Daily Operation Labels',
            'model' => \App\Models\AssignDailyOperationLabel::class,
            'fields' => [
                'id'                        => 'ID',
                'site_id'                   => 'Site',
                'assign_daily_operation_id' => 'Assign Daily Operation ID',
                'cutting_label_id'          => 'Cutting Label ID',
                'created_by'                => 'Created By',
                'updated_by'                => 'Updated By',
                'created_at'                => 'Created At',
                'updated_at'                => 'Updated At',
                'deleted_at'                => 'Deleted At',
            ],
        ],

        'assign_daily_operation_lines' => [
            'label' => 'Assign Daily Operation Lines',
            'model' => \App\Models\AssignDailyOperationLine::class,
            'fields' => [
                'id'                     => 'ID',
                'site_id'                => 'Site',
                'assign_daily_operation_id' => 'Assign Daily Operation ID',
                'production_line_id'     => 'Production Line ID',
                'workstation_id'         => 'Workstation ID',
                'operation_id'           => 'Operation ID',
                'machine_setup_time'     => 'Machine Setup Time',
                'machine_run_time'       => 'Machine Run Time',
                'labor_setup_time'       => 'Labor Setup Time',
                'labor_run_time'         => 'Labor Run Time',
                'target_duration'        => 'Target Duration',
                'target_e'               => 'Target E',
                'target_m'               => 'Target M',
                'measurement_unit'       => 'Measurement Unit',
                'status'                 => 'Status',
                'created_by'             => 'Created By',
                'updated_by'             => 'Updated By',
                'created_at'             => 'Created At',
                'updated_at'             => 'Updated At',
                'deleted_at'             => 'Deleted At',
            ],
        ],

        'assigned_employees' => [
            'label' => 'Assigned Employees',
            'model' => \App\Models\AssignedEmployee::class,
            'fields' => [
                'id'                          => 'ID',
                'site_id'                     => 'Site',
                'user_id'                     => 'User ID',
                'assign_daily_operation_line_id' => 'Operation Line ID',
                'created_by'                  => 'Created By',
                'updated_by'                  => 'Updated By',
                'created_at'                  => 'Created At',
                'updated_at'                  => 'Updated At',
                'deleted_at'                  => 'Deleted At',
            ],
        ],

        'assigned_production_machines' => [
            'label' => 'Assigned Production Machines',
            'model' => \App\Models\AssignedProductionMachine::class,
            'fields' => [
                'id'                         => 'ID',
                'site_id'                    => 'Site',
                'production_machine_id'      => 'Production Machine ID',
                'assign_daily_operation_line_id' => 'Operation Line ID',
                'created_by'                 => 'Created By',
                'updated_by'                 => 'Updated By',
                'created_at'                 => 'Created At',
                'updated_at'                 => 'Updated At',
                'deleted_at'                 => 'Deleted At',
            ],
        ],

        'assigned_supervisors' => [
            'label' => 'Assigned Supervisors',
            'model' => \App\Models\AssignedSupervisor::class,
            'fields' => [
                'id'                          => 'ID',
                'site_id'                     => 'Site',
                'user_id'                     => 'User ID',
                'assign_daily_operation_line_id' => 'Operation Line ID',
                'created_by'                  => 'Created By',
                'updated_by'                  => 'Updated By',
                'created_at'                  => 'Created At',
                'updated_at'                  => 'Updated At',
                'deleted_at'                  => 'Deleted At',
            ],
        ],

        'assigned_third_party_services' => [
            'label' => 'Assigned Third Party Services',
            'model' => \App\Models\AssignedThirdPartyService::class,
            'fields' => [
                'id'                          => 'ID',
                'site_id'                     => 'Site',
                'third_party_service_id'      => 'Third Party Service ID',
                'assign_daily_operation_line_id' => 'Operation Line ID',
                'created_by'                  => 'Created By',
                'updated_by'                  => 'Updated By',
                'created_at'                  => 'Created At',
                'updated_at'                  => 'Updated At',
                'deleted_at'                  => 'Deleted At',
            ],
        ],

        'cash_bank_control_accounts' => [
            'label' => 'Cash/Bank Control Accounts',
            'model' => \App\Models\CashBankControlAccount::class,
            'fields' => [
                'id'                     => 'ID',
                'site_id'                => 'Site',
                'code'                   => 'Code',
                'name'                   => 'Name',
                'account_type'           => 'Account Type',
                'currency'               => 'Currency',
                'opening_balance'        => 'Opening Balance',
                'opening_balance_date'   => 'Opening Balance Date',
                'debit_balance'          => 'Debit Balance',
                'credit_balance'         => 'Credit Balance',
                'balance'                => 'Balance',
                'bank_name'              => 'Bank Name',
                'branch_name'            => 'Branch Name',
                'account_number'         => 'Account Number',
                'swift_code'             => 'SWIFT Code',
                'iban'                   => 'IBAN',
                'bank_address'           => 'Bank Address',
                'tax_number'             => 'Tax Number',
                'is_active'              => 'Is Active',
                'notes'                  => 'Notes',
                'status'                 => 'Status',
                'created_by'             => 'Created By',
                'updated_by'             => 'Updated By',
                'created_at'             => 'Created At',
                'updated_at'             => 'Updated At',
                'deleted_at'             => 'Deleted At',
            ],
        ],

        'categories' => [
            'label' => 'Categories',
            'model' => \App\Models\Category::class,
            'fields' => [
                'id'         => 'ID',
                'site_id'    => 'Site',
                'name'       => 'Name',
                'created_by' => 'Created By',
                'created_at' => 'Created At',
                'updated_at' => 'Updated At',
                'deleted_at' => 'Deleted At',
            ],
        ],

        'chart_of_accounts' => [
            'label' => 'Chart of Accounts',
            'model' => \App\Models\ChartOfAccount::class,
            'fields' => [
                'id'                     => 'ID',
                'site_id'                => 'Site',
                'code'                   => 'Code',
                'name'                   => 'Name',
                'account_type'           => 'Account Type',
                'is_control_account'     => 'Is Control Account',
                'control_account_type'   => 'Control Account Type',
                'statement_type'         => 'Statement Type',
                'sub_category'           => 'Sub Category',
                'description'            => 'Description',
                'vat_output_account_id'  => 'VAT Output Account ID',
                'vat_input_account_id'   => 'VAT Input Account ID',
                'debit_total'            => 'Debit Total',
                'credit_total'           => 'Credit Total',
                'balance'                => 'Balance',
                'debit_total_vat'        => 'Debit Total VAT',
                'credit_total_vat'       => 'Credit Total VAT',
                'balance_vat'            => 'Balance VAT',
                'status'                 => 'Status',
                'created_by'             => 'Created By',
                'updated_by'             => 'Updated By',
                'created_at'             => 'Created At',
                'updated_at'             => 'Updated At',
                'deleted_at'             => 'Deleted At',
            ],
        ],

        'companies' => [
            'label' => 'Companies',
            'model' => \App\Models\Company::class,
            'fields' => [
                'id'             => 'ID',
                'site_id'        => 'Site',
                'name'           => 'Name',
                'address_line_1' => 'Address Line 1',
                'address_line_2' => 'Address Line 2',
                'address_line_3' => 'Address Line 3',
                'city'           => 'City',
                'postal_code'    => 'Postal Code',
                'country'        => 'Country',
                'primary_phone'  => 'Primary Phone',
                'secondary_phone'=> 'Secondary Phone',
                'email'          => 'Email',
                'started_date'   => 'Started Date',
                'special_notes'  => 'Special Notes',
                'updated_by'     => 'Updated By',
                'created_at'     => 'Created At',
                'updated_at'     => 'Updated At',
            ],
        ],

        'currencies' => [
            'label' => 'Currencies',
            'model' => \App\Models\Currency::class,
            'fields' => [
                'id'        => 'ID',
                'site_id'   => 'Site',
                'code'      => 'Code',
                'name'      => 'Name',
                'symbol'    => 'Symbol',
                'is_active' => 'Is Active',
                'created_by'=> 'Created By',
                'updated_by'=> 'Updated By',
                'created_at'=> 'Created At',
                'updated_at'=> 'Updated At',
                'deleted_at'=> 'Deleted At',
            ],
        ],

        'customers' => [
            'label' => 'Customers',
            'model' => \App\Models\Customer::class,
            'fields' => [
                'customer_id'           => 'ID',
                'site_id'               => 'Site',
                'name'                  => 'Name',
                'shop_name'             => 'Shop Name',
                'address_line_1'        => 'Address Line 1',
                'address_line_2'        => 'Address Line 2',
                'city'                  => 'City',
                'zip_code'              => 'Zip Code',
                'email'                 => 'Email',
                'phone_1'               => 'Phone 1',
                'phone_2'               => 'Phone 2',
                'remaining_balance'     => 'Remaining Balance',
                'customer_vat_group_id' => 'VAT Group ID',
                'requested_by'          => 'Requested By',
                'approved_by'           => 'Approved By',
                'created_by'            => 'Created By',
                'updated_by'            => 'Updated By',
                'created_at'            => 'Created At',
                'updated_at'            => 'Updated At',
                'deleted_at'            => 'Deleted At',
            ],
        ],

        'customer_advance_invoices' => [
            'label' => 'Customer Advance Invoices',
            'model' => \App\Models\CustomerAdvanceInvoice::class,
            'fields' => [
                'id'             => 'ID',
                'site_id'        => 'Site',
                'order_type'     => 'Order Type',
                'order_id'       => 'Order ID',
                'customer_id'    => 'Customer ID',
                'grand_total'    => 'Grand Total',
                'amount'         => 'Amount',
                'paid_date'      => 'Paid Date',
                'paid_via'       => 'Paid Via',
                'payment_reference' => 'Payment Reference',
                'cus_invoice_number' => 'Invoice Number',
                'invoice_image'  => 'Invoice Image',
                'status'         => 'Status',
                'created_by'     => 'Created By',
                'updated_by'     => 'Updated By',
                'created_at'     => 'Created At',
                'updated_at'     => 'Updated At',
                'deleted_at'     => 'Deleted At',
            ],
        ],

        'customer_control_accounts' => [
            'label' => 'Customer Control Accounts',
            'model' => \App\Models\CustomerControlAccount::class,
            'fields' => [
                'id'                        => 'ID',
                'site_id'                   => 'Site',
                'customer_id'               => 'Customer',
                'sales_account_id'          => 'Sales Account',
                'export_sales_account_id'   => 'Export Sales Account',
                'sales_return_account_id'   => 'Sales Return Account',
                'sales_discount_account_id' => 'Sales Discount Account',
                'customer_advance_account_id' => 'Customer Advance Account',
                'bad_debt_expense_account_id' => 'Bad Debt Expense Account',
                'allowance_for_doubtful_account_id' => 'Allowance for Doubtful Account',
                'vat_output_account_id'     => 'VAT Output Account',
                'vat_receivable_account_id' => 'VAT Receivable Account',
                'cash_account_id'           => 'Cash Account',
                'bank_account_id'           => 'Bank Account',
                'undeposited_funds_account_id' => 'Undeposited Funds Account',
                'cogs_account_id'           => 'COGS Account',
                'inventory_account_id'      => 'Inventory Account',
                'debit_total'               => 'Debit Total',
                'credit_total'              => 'Credit Total',
                'balance'                   => 'Balance',
                'debit_total_vat'           => 'Debit Total VAT',
                'credit_total_vat'          => 'Credit Total VAT',
                'balance_vat'               => 'Balance VAT',
                'status'                    => 'Status',
                'created_by'                => 'Created By',
                'updated_by'                => 'Updated By',
                'created_at'                => 'Created At',
                'updated_at'                => 'Updated At',
                'deleted_at'                => 'Deleted At',
            ],
        ],

        'customer_orders' => [
            'label' => 'Customer Orders',
            'model' => \App\Models\CustomerOrder::class,
            'fields' => [
                'order_id'          => 'Order ID',
                'site_id'           => 'Site',
                'name'              => 'Order Name',
                'wanted_delivery_date' => 'Delivery Date',
                'customer_id'       => 'Customer',
                'special_notes'     => 'Special Notes',
                'status'            => 'Status',
                'grand_total'       => 'Grand Total',
                'remaining_balance' => 'Remaining Balance',
                'random_code'       => 'Random Code',
                'created_by'        => 'Created By',
                'updated_by'        => 'Updated By',
                'created_at'        => 'Created At',
                'updated_at'        => 'Updated At',
                'deleted_at'        => 'Deleted At',
            ],
        ],

        'customer_order_descriptions' => [
            'label' => 'Customer Order Description Items',
            'model' => \App\Models\CustomerOrderDescription::class,
            'fields' => [
                'id'                 => 'ID',
                'site_id'            => 'Site',
                'customer_order_id'  => 'Customer Order',
                'item_name'          => 'Item Name',
                'variation_name'     => 'Variation Name',
                'quantity'           => 'Quantity',
                'price'              => 'Price',
                'total'              => 'Total',
                'note'               => 'Note',
                'is_variation'       => 'Is Variation',
                'created_by'         => 'Created By',
                'updated_by'         => 'Updated By',
                'created_at'         => 'Created At',
                'updated_at'         => 'Updated At',
                'deleted_at'         => 'Deleted At',
            ],
        ],

        'customer_vat_groups' => [
            'label' => 'Customer VAT Groups',
            'model' => \App\Models\CustomerVatGroup::class,
            'fields' => [
                'id'             => 'ID',
                'site_id'        => 'Site',
                'code'           => 'Code',
                'vat_group_name' => 'VAT Group Name',
                'vat_rate'       => 'VAT Rate',
                'status'         => 'Status',
                'created_by'     => 'Created By',
                'updated_by'     => 'Updated By',
                'created_at'     => 'Created At',
                'updated_at'     => 'Updated At',
                'deleted_at'     => 'Deleted At',
            ],
        ],

        'cutting_by_products' => [
            'label' => 'Cutting By Products',
            'model' => \App\Models\CuttingByProduct::class,
            'fields' => [
                'id'                 => 'ID',
                'site_id'            => 'Site',
                'cutting_record_id'  => 'Cutting Record',
                'item_id'            => 'Item',
                'amount'             => 'Amount',
                'unit'               => 'Unit',
                'location_id'        => 'Location',
                'created_by'         => 'Created By',
                'updated_by'         => 'Updated By',
                'created_at'         => 'Created At',
                'updated_at'         => 'Updated At',
                'deleted_at'         => 'Deleted At',
            ],
        ],

        'cutting_employees' => [
            'label' => 'Cutting Employees',
            'model' => \App\Models\CuttingEmployee::class,
            'fields' => [
                'id'                => 'ID',
                'site_id'           => 'Site',
                'cutting_record_id' => 'Cutting Record',
                'employee_id'       => 'Employee',
                'pieces_cut'        => 'Pieces Cut',
                'supervisor_id'     => 'Supervisor',
                'notes'             => 'Notes',
                'created_by'        => 'Created By',
                'updated_by'        => 'Updated By',
                'created_at'        => 'Created At',
                'updated_at'        => 'Updated At',
                'deleted_at'        => 'Deleted At',
            ],
        ],

        'cutting_inventory_wastes' => [
            'label' => 'Cutting Inventory Wastes',
            'model' => \App\Models\CuttingInventoryWaste::class,
            'fields' => [
                'id'                => 'ID',
                'site_id'           => 'Site',
                'cutting_record_id' => 'Cutting Record',
                'item_id'           => 'Item',
                'amount'            => 'Amount',
                'unit'              => 'Unit',
                'location_id'       => 'Location',
                'created_by'        => 'Created By',
                'updated_by'        => 'Updated By',
                'created_at'        => 'Created At',
                'updated_at'        => 'Updated At',
                'deleted_at'        => 'Deleted At',
            ],
        ],

        'cutting_labels' => [
            'label' => 'Cutting Labels',
            'model' => \App\Models\CuttingLabel::class,
            'fields' => [
                'id'                => 'ID',
                'site_id'           => 'Site',
                'cutting_record_id' => 'Cutting Record',
                'order_type'        => 'Order Type',
                'order_id'          => 'Order',
                'order_item_id'     => 'Order Item',
                'order_variation_id'=> 'Order Variation',
                'quantity'          => 'Quantity',
                'label'             => 'Label',
                'status'            => 'Status',
                'barcode'           => 'Barcode',
                'barcode_id'        => 'Barcode ID',
                'created_by'        => 'Created By',
                'updated_by'        => 'Updated By',
                'created_at'        => 'Created At',
                'updated_at'        => 'Updated At',
                'deleted_at'        => 'Deleted At',
            ],
        ],

        'cutting_non_inventory_waste' => [
            'label' => 'Cutting Non-Inventory Waste',
            'model' => \App\Models\CuttingNonInventoryWaste::class,
            'fields' => [
                'id'                 => 'ID',
                'site_id'            => 'Site',
                'cutting_record_id'  => 'Cutting Record',
                'item_id'            => 'Item',
                'amount'             => 'Amount',
                'unit'               => 'Unit',
                'created_by'         => 'Created By',
                'updated_by'         => 'Updated By',
                'created_at'         => 'Created At',
                'updated_at'         => 'Updated At',
                'deleted_at'         => 'Deleted At',
            ],
        ],

        'cutting_order_items' => [
            'label' => 'Cutting Order Items',
            'model' => \App\Models\CuttingOrderItem::class,
            'fields' => [
                'id'                 => 'ID',
                'site_id'            => 'Site',
                'cutting_record_id'  => 'Cutting Record',
                'item_type'          => 'Item Type',
                'item_id'            => 'Item',
                'quantity'           => 'Quantity',
                'created_by'         => 'Created By',
                'updated_by'         => 'Updated By',
                'created_at'         => 'Created At',
                'updated_at'         => 'Updated At',
                'deleted_at'         => 'Deleted At',
            ],
        ],

        'cutting_order_variations' => [
            'label' => 'Cutting Order Variations',
            'model' => \App\Models\CuttingOrderVariation::class,
            'fields' => [
                'id'               => 'ID',
                'site_id'          => 'Site',
                'cutting_record_id'=> 'Cutting Record',
                'order_item_id'    => 'Order Item',
                'variation_type'   => 'Variation Type',
                'variation_id'     => 'Variation ID',
                'quantity'         => 'Quantity',
                'created_by'       => 'Created By',
                'updated_by'       => 'Updated By',
                'created_at'       => 'Created At',
                'updated_at'       => 'Updated At',
                'deleted_at'       => 'Deleted At',
            ],
        ],

        'cutting_quality_controls' => [
            'label' => 'Cutting Quality Controls',
            'model' => \App\Models\CuttingQualityControl::class,
            'fields' => [
                'id'                  => 'ID',
                'site_id'             => 'Site',
                'cutting_record_id'   => 'Cutting Record',
                'qc_user_id'          => 'QC User',
                'inspected_quantity'  => 'Inspected Quantity',
                'accepted_quantity'   => 'Accepted Quantity',
                'rejected_quantity'   => 'Rejected Quantity',
                'notes'               => 'Notes',
                'created_by'          => 'Created By',
                'updated_by'          => 'Updated By',
                'created_at'          => 'Created At',
                'updated_at'          => 'Updated At',
                'deleted_at'          => 'Deleted At',
            ],
        ],

        'cutting_records' => [
            'label' => 'Cutting Records',
            'model' => \App\Models\CuttingRecord::class,
            'fields' => [
                'id'                    => 'ID',
                'site_id'               => 'Site',
                'order_type'            => 'Order Type',
                'order_id'              => 'Order',
                'cutting_station_id'    => 'Cutting Station',
                'release_material_id'   => 'Release Material',
                'operation_date'        => 'Operation Date',
                'operated_time_from'    => 'Operated Time From',
                'operated_time_to'      => 'Operated Time To',
                'notes'                 => 'Notes',
                'created_by'            => 'Created By',
                'updated_by'            => 'Updated By',
                'created_at'            => 'Created At',
                'updated_at'            => 'Updated At',
                'deleted_at'            => 'Deleted At',
            ],
        ],

        'cutting_stations' => [
            'label' => 'Cutting Stations',
            'model' => \App\Models\CuttingStation::class,
            'fields' => [
                'id'          => 'ID',
                'site_id'     => 'Site',
                'name'        => 'Name',
                'description' => 'Description',
                'created_by'  => 'Created By',
                'updated_by'  => 'Updated By',
                'created_at'  => 'Created At',
                'updated_at'  => 'Updated At',
                'deleted_at'  => 'Deleted At',
            ],
        ],

        'delivery_methods' => [
            'label' => 'Delivery Methods',
            'model' => \App\Models\DeliveryMethod::class,
            'fields' => [
                'id'          => 'ID',
                'site_id'     => 'Site',
                'name'        => 'Name',
                'description' => 'Description',
                'created_by'  => 'Created By',
                'updated_by'  => 'Updated By',
                'created_at'  => 'Created At',
                'updated_at'  => 'Updated At',
                'deleted_at'  => 'Deleted At',
            ],
        ],

        'delivery_terms' => [
            'label' => 'Delivery Terms',
            'model' => \App\Models\DeliveryTerm::class,
            'fields' => [
                'id'          => 'ID',
                'site_id'     => 'Site',
                'name'        => 'Name',
                'description' => 'Description',
                'created_by'  => 'Created By',
                'updated_by'  => 'Updated By',
                'created_at'  => 'Created At',
                'updated_at'  => 'Updated At',
                'deleted_at'  => 'Deleted At',
            ],
        ],

        'emergency_stocks' => [
            'label' => 'Emergency Stocks',
            'model' => \App\Models\EmergencyStock::class,
            'fields' => [
                'id'           => 'ID',
                'site_id'      => 'Site',
                'item_id'      => 'Item',
                'location_id'  => 'Location',
                'quantity'     => 'Quantity',
                'cost'         => 'Cost',
                'updated_date' => 'Updated Date',
                'received_date'=> 'Received Date',
                'created_by'   => 'Created By',
                'updated_by'   => 'Updated By',
                'created_at'   => 'Created At',
                'updated_at'   => 'Updated At',
                'deleted_at'   => 'Deleted At',
            ],
        ],

        'end_of_day_reports' => [
            'label' => 'End of Day Reports',
            'model' => \App\Models\EndOfDayReport::class,
            'fields' => [
                'id'                        => 'ID',
                'site_id'                   => 'Site',
                'operated_date'             => 'Operated Date',
                'recorded_operations_count' => 'Recorded Operations Count',
                'status'                    => 'Status',
                'created_by'                => 'Created By',
                'updated_by'                => 'Updated By',
                'created_at'                => 'Created At',
                'updated_at'                => 'Updated At',
                'deleted_at'                => 'Deleted At',
            ],
        ],

        'end_of_day_report_operations' => [
            'label' => 'End of Day Report Operations',
            'model' => \App\Models\EndOfDayReportOperation::class,
            'fields' => [
                'id'                        => 'ID',
                'site_id'                   => 'Site',
                'end_of_day_report_id'      => 'End of Day Report',
                'enter_performance_record_id' => 'Performance Record',
                'assign_daily_operation_id' => 'Assigned Operation',
                'operation_line_id'         => 'Operation Line',
                'temporary_operation_id'    => 'Temporary Operation',
                'created_by'                => 'Created By',
                'updated_by'                => 'Updated By',
                'created_at'                => 'Created At',
                'updated_at'                => 'Updated At',
                'deleted_at'                => 'Deleted At',
            ],
        ],

        'enter_by_products_performance' => [
            'label' => 'Enter By-Products Performance',
            'model' => \App\Models\EnterByProductsPerformance::class,
            'fields' => [
                'id'                        => 'ID',
                'site_id'                   => 'Site',
                'enter_performance_record_id' => 'Performance Record',
                'item_id'                   => 'Item',
                'amount'                    => 'Amount',
                'uom'                       => 'Unit of Measure',
                'location_id'               => 'Location',
                'created_by'                => 'Created By',
                'updated_by'                => 'Updated By',
                'created_at'                => 'Created At',
                'updated_at'                => 'Updated At',
                'deleted_at'                => 'Deleted At',
            ],
        ],

        'enter_employee_label_performance' => [
            'label' => 'Enter Employee Label Performance',
            'model' => \App\Models\EnterEmployeeLabelPerformance::class,
            'fields' => [
                'id'                        => 'ID',
                'site_id'                   => 'Site',
                'enter_performance_record_id' => 'Performance Record',
                'cutting_label_id'          => 'Cutting Label',
                'employee_id'               => 'Employee',
                'created_by'                => 'Created By',
                'updated_by'                => 'Updated By',
                'created_at'                => 'Created At',
                'updated_at'                => 'Updated At',
                'deleted_at'                => 'Deleted At',
            ],
        ],

        'enter_employee_performance' => [
            'label' => 'Enter Employee Performance',
            'model' => \App\Models\EnterEmployeePerformance::class,
            'fields' => [
                'id'                        => 'ID',
                'site_id'                   => 'Site',
                'enter_performance_record_id' => 'Performance Record',
                'employee_id'               => 'Employee',
                'emp_production'            => 'Employee Production',
                'emp_downtime'              => 'Employee Downtime',
                'created_by'                => 'Created By',
                'updated_by'                => 'Updated By',
                'created_at'                => 'Created At',
                'updated_at'                => 'Updated At',
                'deleted_at'                => 'Deleted At',
            ],
        ],

        'enter_inv_waste_performance' => [
            'label' => 'Enter Inventory Waste Performance',
            'model' => \App\Models\EnterInvWastePerformance::class,
            'fields' => [
                'id'                        => 'ID',
                'site_id'                   => 'Site',
                'enter_performance_record_id' => 'Performance Record',
                'waste'                     => 'Waste Amount',
                'uom'                       => 'Unit of Measure',
                'item_id'                   => 'Item',
                'location_id'               => 'Location',
                'created_by'                => 'Created By',
                'updated_by'                => 'Updated By',
                'created_at'                => 'Created At',
                'updated_at'                => 'Updated At',
                'deleted_at'                => 'Deleted At',
            ],
        ],

        'enter_machine_label_performance' => [
            'label' => 'Enter Machine Label Performance',
            'model' => \App\Models\EnterMachineLabelPerformance::class,
            'fields' => [
                'id'                          => 'ID',
                'site_id'                     => 'Site',
                'enter_performance_record_id' => 'Performance Record',
                'cutting_label_id'            => 'Cutting Label',
                'machine_id'                  => 'Machine',
                'created_by'                  => 'Created By',
                'updated_by'                  => 'Updated By',
                'created_at'                  => 'Created At',
                'updated_at'                  => 'Updated At',
                'deleted_at'                  => 'Deleted At',
            ],
        ],

        'enter_machine_performance' => [
            'label' => 'Enter Machine Performance',
            'model' => \App\Models\EnterMachinePerformance::class,
            'fields' => [
                'id'                          => 'ID',
                'site_id'                     => 'Site',
                'enter_performance_record_id' => 'Performance Record',
                'machine_id'                  => 'Machine',
                'machine_downtime'            => 'Machine Downtime',
                'machine_notes'               => 'Machine Notes',
                'created_by'                  => 'Created By',
                'updated_by'                  => 'Updated By',
                'created_at'                  => 'Created At',
                'updated_at'                  => 'Updated At',
                'deleted_at'                  => 'Deleted At',
            ],
        ],

        'enter_non_inv_performance' => [
            'label' => 'Enter Non-Inventory Performance',
            'model' => \App\Models\EnterNonInvPerformance::class,
            'fields' => [
                'id'                          => 'ID',
                'site_id'                     => 'Site',
                'enter_performance_record_id' => 'Performance Record',
                'amount'                      => 'Amount',
                'item_id'                     => 'Non-Inventory Item',
                'uom'                         => 'Unit',
                'created_by'                  => 'Created By',
                'updated_by'                  => 'Updated By',
                'created_at'                  => 'Created At',
                'updated_at'                  => 'Updated At',
                'deleted_at'                  => 'Deleted At',
            ],
        ],

        'enter_performance_record' => [
            'label' => 'Enter Performance Records',
            'model' => \App\Models\EnterPerformanceRecord::class,
            'fields' => [
                'id'                         => 'ID',
                'site_id'                    => 'Site',
                'assign_daily_operation_id'  => 'Assigned Daily Operation',
                'assign_daily_operation_line_id' => 'Operation Line',
                'operation_date'             => 'Operation Date',
                'operated_time_from'         => 'Operated Time From',
                'operated_time_to'           => 'Operated Time To',
                'actual_machine_setup_time'  => 'Actual Machine Setup Time',
                'actual_machine_run_time'    => 'Actual Machine Run Time',
                'actual_employee_setup_time' => 'Actual Employee Setup Time',
                'actual_employee_run_time'   => 'Actual Employee Run Time',
                'status'                     => 'Status',
                'created_by'                 => 'Created By',
                'updated_by'                 => 'Updated By',
                'created_at'                 => 'Created At',
                'updated_at'                 => 'Updated At',
                'deleted_at'                 => 'Deleted At',
            ],
        ],

        'enter_qc_label_performance' => [
            'label' => 'QC Label Performance',
            'model' => \App\Models\EnterQcLabelPerformance::class,
            'fields' => [
                'id'                         => 'ID',
                'site_id'                    => 'Site',
                'enter_performance_record_id'=> 'Performance Record',
                'cutting_label_id'           => 'Cutting Label',
                'result'                     => 'QC Result',
                'created_by'                 => 'Created By',
                'updated_by'                 => 'Updated By',
                'created_at'                 => 'Created At',
                'updated_at'                 => 'Updated At',
                'deleted_at'                 => 'Deleted At',
            ],
        ],

        'enter_qc_performance' => [
            'label' => 'QC Performance',
            'model' => \App\Models\EnterQcPerformance::class,
            'fields' => [
                'id'                          => 'ID',
                'site_id'                     => 'Site',
                'enter_performance_record_id' => 'Performance Record',
                'no_of_passed_items'          => 'Passed Items',
                'no_of_failed_items'          => 'Failed Items',
                'action_type'                 => 'Action Type',
                'cutting_station_id'          => 'Cutting Station',
                'assign_operation_line_id'    => 'Assign Operation Line',
                'created_by'                  => 'Created By',
                'updated_by'                  => 'Updated By',
                'created_at'                  => 'Created At',
                'updated_at'                  => 'Updated At',
                'deleted_at'                  => 'Deleted At',
            ],
        ],

        'enter_service_performance' => [
            'label' => 'Service Performance',
            'model' => \App\Models\EnterServicePerformance::class,
            'fields' => [
                'id'                         => 'ID',
                'site_id'                    => 'Site',
                'enter_performance_record_id'=> 'Performance Record',
                'service_id'                 => 'Service',
                'service_process_id'         => 'Service Process',
                'used_amount'                => 'Used Amount',
                'unit_rate'                  => 'Unit Rate',
                'total_cost'                 => 'Total Cost',
                'created_by'                 => 'Created By',
                'updated_by'                 => 'Updated By',
                'created_at'                 => 'Created At',
                'updated_at'                 => 'Updated At',
                'deleted_at'                 => 'Deleted At',
            ],
        ],

        'enter_supervisor_performance' => [
            'label' => 'Supervisor Performance',
            'model' => \App\Models\EnterSupervisorPerformance::class,
            'fields' => [
                'id'                         => 'ID',
                'site_id'                    => 'Site',
                'enter_performance_record_id'=> 'Performance Record',
                'supervisor_id'              => 'Supervisor',
                'accepted_qty'               => 'Accepted Quantity',
                'rejected_qty'               => 'Rejected Quantity',
                'supervisored_qty'           => 'Supervised Quantity',
                'sup_downtime'               => 'Supervisor Downtime',
                'sup_notes'                  => 'Notes',
                'created_by'                 => 'Created By',
                'updated_by'                 => 'Updated By',
                'created_at'                 => 'Created At',
                'updated_at'                 => 'Updated At',
                'deleted_at'                 => 'Deleted At',
            ],
        ],

        'final_product_qcs' => [
            'label' => 'Final Product QC',
            'model' => \App\Models\FinalProductQC::class,
            'fields' => [
                'id'             => 'ID',
                'site_id'        => 'Site',
                'order_type'     => 'Order Type',
                'order_id'       => 'Order ID',
                'qc_officer_id'  => 'QC Officer',
                'inspected_date' => 'Inspected Date',
                'result'         => 'Result',
                'created_by'     => 'Created By',
                'updated_by'     => 'Updated By',
                'created_at'     => 'Created At',
                'updated_at'     => 'Updated At',
                'deleted_at'     => 'Deleted At',
            ],
        ],

        'final_product_qc_labels' => [
            'label' => 'Final Product QC Labels',
            'model' => \App\Models\FinalProductQCLabel::class,
            'fields' => [
                'id'                  => 'ID',
                'site_id'             => 'Site',
                'final_product_qc_id' => 'Final Product QC',
                'cutting_label_id'    => 'Cutting Label',
                'result'              => 'Result',
                'created_by'          => 'Created By',
                'updated_by'          => 'Updated By',
                'created_at'          => 'Created At',
                'updated_at'          => 'Updated At',
                'deleted_at'          => 'Deleted At',
            ],
        ],

        'general_ledger_entries' => [
            'label' => 'General Ledger Entries',
            'model' => \App\Models\GeneralLedgerEntry::class,
            'fields' => [
                'id'                        => 'ID',
                'site_id'                   => 'Site',
                'entry_code'                => 'Entry Code',
                'account_id'                => 'Account',
                'source_table'              => 'Source Table',
                'source_id'                 => 'Source ID',
                'control_account_table'     => 'Control Account Table',
                'control_account_record_id' => 'Control Account Record ID',
                'entry_date'                => 'Entry Date',
                'debit'                     => 'Debit',
                'credit'                    => 'Credit',
                'transaction_name'          => 'Transaction Name',
                'description'               => 'Description',
                'created_by'                => 'Created By',
                'updated_by'                => 'Updated By',
                'created_at'                => 'Created At',
                'updated_at'                => 'Updated At',
                'deleted_at'                => 'Deleted At',
            ],
        ],

    ],
];
